/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerCardapioPedido;
import javax.swing.JCheckBox;
import javax.swing.JTextField;

/**
 *
 * @author Casa
 */
public class CardapioPedido extends javax.swing.JFrame {

    private final ControllerCardapioPedido controller;
    /**
     * Creates new form MenuPrincipal
     */
    public CardapioPedido() {
        initComponents();
        this.controller = new ControllerCardapioPedido(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVoltar = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        lblPreco1 = new javax.swing.JLabel();
        checkBoxPizza2 = new javax.swing.JCheckBox();
        lblPreco2 = new javax.swing.JLabel();
        checkBoxPizza3 = new javax.swing.JCheckBox();
        lblPreco3 = new javax.swing.JLabel();
        checkBoxPizza4 = new javax.swing.JCheckBox();
        lblPreco4 = new javax.swing.JLabel();
        checkBoxPizza5 = new javax.swing.JCheckBox();
        lblPreco5 = new javax.swing.JLabel();
        checkBoxPizza6 = new javax.swing.JCheckBox();
        lblPreco6 = new javax.swing.JLabel();
        checkBoxPizza7 = new javax.swing.JCheckBox();
        lblPreco7 = new javax.swing.JLabel();
        checkBoxPizza8 = new javax.swing.JCheckBox();
        lblPreco8 = new javax.swing.JLabel();
        checkBoxPizza9 = new javax.swing.JCheckBox();
        lblPreco9 = new javax.swing.JLabel();
        checkBoxPizza1 = new javax.swing.JCheckBox();
        lblTotal = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        btnAvancar = new javax.swing.JButton();
        lblFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVoltar.setBackground(new java.awt.Color(255, 255, 255));
        btnVoltar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lblTitulo.setFont(new java.awt.Font("Monotype Corsiva", 1, 48)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Cardápio");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, 170, -1));

        lblPreco1.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        lblPreco1.setForeground(new java.awt.Color(255, 255, 255));
        lblPreco1.setText("R$ 44,00");
        getContentPane().add(lblPreco1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 130, -1));

        checkBoxPizza2.setBackground(new java.awt.Color(255, 255, 255));
        checkBoxPizza2.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        checkBoxPizza2.setForeground(new java.awt.Color(255, 255, 255));
        checkBoxPizza2.setText("Aliche");
        checkBoxPizza2.setPreferredSize(new java.awt.Dimension(213, 41));
        checkBoxPizza2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxPizza2ActionPerformed(evt);
            }
        });
        getContentPane().add(checkBoxPizza2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 250, -1));

        lblPreco2.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        lblPreco2.setForeground(new java.awt.Color(255, 255, 255));
        lblPreco2.setText("R$ 35,00");
        getContentPane().add(lblPreco2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 130, -1));

        checkBoxPizza3.setBackground(new java.awt.Color(255, 255, 255));
        checkBoxPizza3.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        checkBoxPizza3.setForeground(new java.awt.Color(255, 255, 255));
        checkBoxPizza3.setText("Baurú");
        checkBoxPizza3.setPreferredSize(new java.awt.Dimension(213, 41));
        checkBoxPizza3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxPizza3ActionPerformed(evt);
            }
        });
        getContentPane().add(checkBoxPizza3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 250, -1));

        lblPreco3.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        lblPreco3.setForeground(new java.awt.Color(255, 255, 255));
        lblPreco3.setText("R$ 34,00");
        getContentPane().add(lblPreco3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 130, -1));

        checkBoxPizza4.setBackground(new java.awt.Color(255, 255, 255));
        checkBoxPizza4.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        checkBoxPizza4.setForeground(new java.awt.Color(255, 255, 255));
        checkBoxPizza4.setText("Baiana");
        checkBoxPizza4.setPreferredSize(new java.awt.Dimension(213, 41));
        checkBoxPizza4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxPizza4ActionPerformed(evt);
            }
        });
        getContentPane().add(checkBoxPizza4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 250, -1));

        lblPreco4.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        lblPreco4.setForeground(new java.awt.Color(255, 255, 255));
        lblPreco4.setText("R$ 37,00");
        getContentPane().add(lblPreco4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 130, -1));

        checkBoxPizza5.setBackground(new java.awt.Color(255, 255, 255));
        checkBoxPizza5.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        checkBoxPizza5.setForeground(new java.awt.Color(255, 255, 255));
        checkBoxPizza5.setText("Brasileira");
        checkBoxPizza5.setPreferredSize(new java.awt.Dimension(213, 41));
        checkBoxPizza5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxPizza5ActionPerformed(evt);
            }
        });
        getContentPane().add(checkBoxPizza5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 480, 250, -1));

        lblPreco5.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        lblPreco5.setForeground(new java.awt.Color(255, 255, 255));
        lblPreco5.setText("R$ 40,00");
        getContentPane().add(lblPreco5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 480, 130, -1));

        checkBoxPizza6.setBackground(new java.awt.Color(255, 255, 255));
        checkBoxPizza6.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        checkBoxPizza6.setForeground(new java.awt.Color(255, 255, 255));
        checkBoxPizza6.setText("Paraguaia");
        checkBoxPizza6.setPreferredSize(new java.awt.Dimension(213, 41));
        checkBoxPizza6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxPizza6ActionPerformed(evt);
            }
        });
        getContentPane().add(checkBoxPizza6, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 160, 310, -1));

        lblPreco6.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        lblPreco6.setForeground(new java.awt.Color(255, 255, 255));
        lblPreco6.setText("R$ 42,00");
        getContentPane().add(lblPreco6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 160, 130, -1));

        checkBoxPizza7.setBackground(new java.awt.Color(255, 255, 255));
        checkBoxPizza7.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        checkBoxPizza7.setForeground(new java.awt.Color(255, 255, 255));
        checkBoxPizza7.setText("Portuguesa");
        checkBoxPizza7.setPreferredSize(new java.awt.Dimension(213, 41));
        checkBoxPizza7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxPizza7ActionPerformed(evt);
            }
        });
        getContentPane().add(checkBoxPizza7, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 240, 310, -1));

        lblPreco7.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        lblPreco7.setForeground(new java.awt.Color(255, 255, 255));
        lblPreco7.setText("R$ 39,00");
        getContentPane().add(lblPreco7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 240, 130, -1));

        checkBoxPizza8.setBackground(new java.awt.Color(255, 255, 255));
        checkBoxPizza8.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        checkBoxPizza8.setForeground(new java.awt.Color(255, 255, 255));
        checkBoxPizza8.setText("Vegetariana");
        checkBoxPizza8.setPreferredSize(new java.awt.Dimension(213, 41));
        checkBoxPizza8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxPizza8ActionPerformed(evt);
            }
        });
        getContentPane().add(checkBoxPizza8, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 320, 310, -1));

        lblPreco8.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        lblPreco8.setForeground(new java.awt.Color(255, 255, 255));
        lblPreco8.setText("R$ 40,00");
        getContentPane().add(lblPreco8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 320, 130, -1));

        checkBoxPizza9.setBackground(new java.awt.Color(255, 255, 255));
        checkBoxPizza9.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        checkBoxPizza9.setForeground(new java.awt.Color(255, 255, 255));
        checkBoxPizza9.setText("Frango com Catupiry");
        checkBoxPizza9.setPreferredSize(new java.awt.Dimension(213, 41));
        checkBoxPizza9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxPizza9ActionPerformed(evt);
            }
        });
        getContentPane().add(checkBoxPizza9, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 400, 310, -1));

        lblPreco9.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        lblPreco9.setForeground(new java.awt.Color(255, 255, 255));
        lblPreco9.setText("R$ 38,00");
        getContentPane().add(lblPreco9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 400, 130, -1));

        checkBoxPizza1.setBackground(new java.awt.Color(255, 255, 255));
        checkBoxPizza1.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        checkBoxPizza1.setForeground(new java.awt.Color(255, 255, 255));
        checkBoxPizza1.setText("À Moda da Casa");
        checkBoxPizza1.setPreferredSize(new java.awt.Dimension(213, 41));
        checkBoxPizza1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxPizza1ActionPerformed(evt);
            }
        });
        getContentPane().add(checkBoxPizza1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 250, -1));

        lblTotal.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblTotal.setText("Total:");
        getContentPane().add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 510, 80, -1));

        txtTotal.setEditable(false);
        txtTotal.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtTotal.setForeground(new java.awt.Color(0, 153, 0));
        txtTotal.setPreferredSize(new java.awt.Dimension(118, 41));
        getContentPane().add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 510, 190, 40));

        btnAvancar.setBackground(new java.awt.Color(255, 255, 255));
        btnAvancar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnAvancar.setText("Avançar");
        btnAvancar.setPreferredSize(new java.awt.Dimension(118, 41));
        btnAvancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvancarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAvancar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 510, -1, -1));

        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/cardapio.png"))); // NOI18N
        getContentPane().add(lblFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        
        controller.VoltarParaMenu();
        
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnAvancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvancarActionPerformed
        
        controller.navegarParaInformacoes();
        
    }//GEN-LAST:event_btnAvancarActionPerformed

    private void checkBoxPizza1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxPizza1ActionPerformed
        
        controller.clicarNaPizza(this.checkBoxPizza1, 44.00);
        
    }//GEN-LAST:event_checkBoxPizza1ActionPerformed

    private void checkBoxPizza2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxPizza2ActionPerformed
        
        controller.clicarNaPizza(this.checkBoxPizza2, 35.00);
        
    }//GEN-LAST:event_checkBoxPizza2ActionPerformed

    private void checkBoxPizza3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxPizza3ActionPerformed
        
        controller.clicarNaPizza(this.checkBoxPizza3, 34.00);
        
    }//GEN-LAST:event_checkBoxPizza3ActionPerformed

    private void checkBoxPizza4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxPizza4ActionPerformed
        
        controller.clicarNaPizza(this.checkBoxPizza4, 37.00);
        
    }//GEN-LAST:event_checkBoxPizza4ActionPerformed

    private void checkBoxPizza5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxPizza5ActionPerformed
        
        controller.clicarNaPizza(this.checkBoxPizza5, 40.00);
        
    }//GEN-LAST:event_checkBoxPizza5ActionPerformed

    private void checkBoxPizza6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxPizza6ActionPerformed
        
        controller.clicarNaPizza(this.checkBoxPizza6, 42.00);
        
    }//GEN-LAST:event_checkBoxPizza6ActionPerformed

    private void checkBoxPizza7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxPizza7ActionPerformed
        
        controller.clicarNaPizza(this.checkBoxPizza7, 39.00);
        
    }//GEN-LAST:event_checkBoxPizza7ActionPerformed

    private void checkBoxPizza8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxPizza8ActionPerformed
        
        controller.clicarNaPizza(this.checkBoxPizza8, 40.00);
        
    }//GEN-LAST:event_checkBoxPizza8ActionPerformed

    private void checkBoxPizza9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxPizza9ActionPerformed
        
        controller.clicarNaPizza(this.checkBoxPizza9, 38.00);
        
    }//GEN-LAST:event_checkBoxPizza9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CardapioPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CardapioPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CardapioPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CardapioPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CardapioPedido().setVisible(true);
            }
        });
    }

    public JCheckBox getCheckBoxPizza1() {
        return checkBoxPizza1;
    }

    public void setCheckBoxPizza1(JCheckBox checkBoxPizza1) {
        this.checkBoxPizza1 = checkBoxPizza1;
    }

    public JCheckBox getCheckBoxPizza2() {
        return checkBoxPizza2;
    }

    public void setCheckBoxPizza2(JCheckBox checkBoxPizza2) {
        this.checkBoxPizza2 = checkBoxPizza2;
    }

    public JCheckBox getCheckBoxPizza3() {
        return checkBoxPizza3;
    }

    public void setCheckBoxPizza3(JCheckBox checkBoxPizza3) {
        this.checkBoxPizza3 = checkBoxPizza3;
    }

    public JCheckBox getCheckBoxPizza4() {
        return checkBoxPizza4;
    }

    public void setCheckBoxPizza4(JCheckBox checkBoxPizza4) {
        this.checkBoxPizza4 = checkBoxPizza4;
    }

    public JCheckBox getCheckBoxPizza5() {
        return checkBoxPizza5;
    }

    public void setCheckBoxPizza5(JCheckBox checkBoxPizza5) {
        this.checkBoxPizza5 = checkBoxPizza5;
    }

    public JCheckBox getCheckBoxPizza6() {
        return checkBoxPizza6;
    }

    public void setCheckBoxPizza6(JCheckBox checkBoxPizza6) {
        this.checkBoxPizza6 = checkBoxPizza6;
    }

    public JCheckBox getCheckBoxPizza7() {
        return checkBoxPizza7;
    }

    public void setCheckBoxPizza7(JCheckBox checkBoxPizza7) {
        this.checkBoxPizza7 = checkBoxPizza7;
    }

    public JCheckBox getCheckBoxPizza8() {
        return checkBoxPizza8;
    }

    public void setCheckBoxPizza8(JCheckBox checkBoxPizza8) {
        this.checkBoxPizza8 = checkBoxPizza8;
    }

    public JCheckBox getCheckBoxPizza9() {
        return checkBoxPizza9;
    }

    public void setCheckBoxPizza9(JCheckBox checkBoxPizza9) {
        this.checkBoxPizza9 = checkBoxPizza9;
    }

    public JTextField getTxtTotal() {
        return txtTotal;
    }

    public void setTxtTotal(JTextField txtTotal) {
        this.txtTotal = txtTotal;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvancar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JCheckBox checkBoxPizza1;
    private javax.swing.JCheckBox checkBoxPizza2;
    private javax.swing.JCheckBox checkBoxPizza3;
    private javax.swing.JCheckBox checkBoxPizza4;
    private javax.swing.JCheckBox checkBoxPizza5;
    private javax.swing.JCheckBox checkBoxPizza6;
    private javax.swing.JCheckBox checkBoxPizza7;
    private javax.swing.JCheckBox checkBoxPizza8;
    private javax.swing.JCheckBox checkBoxPizza9;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JLabel lblPreco1;
    private javax.swing.JLabel lblPreco2;
    private javax.swing.JLabel lblPreco3;
    private javax.swing.JLabel lblPreco4;
    private javax.swing.JLabel lblPreco5;
    private javax.swing.JLabel lblPreco6;
    private javax.swing.JLabel lblPreco7;
    private javax.swing.JLabel lblPreco8;
    private javax.swing.JLabel lblPreco9;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
