/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerInformacoes;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import model.Pedido;

/**
 *
 * @author Casa
 */
public class Informacoes extends javax.swing.JFrame {

    private final ControllerInformacoes controller;
    
    /**
     * Creates new form MenuPrincipal
     */
    public Informacoes() {
        initComponents();
        this.controller = new ControllerInformacoes(this);
        
        controller.esconderCamposTroco();
    }
    
    public void setarPedido(Pedido pedido){
        controller.setPedido(pedido);
        
        controller.existeInformacoes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        btnVoltar = new javax.swing.JButton();
        lblTitulo1 = new javax.swing.JLabel();
        lblTitulo2 = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblBairro = new javax.swing.JLabel();
        lblRua = new javax.swing.JLabel();
        lblNumero = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtBairro = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        txtRua = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        lblPagamento = new javax.swing.JLabel();
        radioDebito = new javax.swing.JRadioButton();
        radioCredito = new javax.swing.JRadioButton();
        radioDinheiro = new javax.swing.JRadioButton();
        lblTroco = new javax.swing.JLabel();
        radioSim = new javax.swing.JRadioButton();
        radioNao = new javax.swing.JRadioButton();
        lblTrocoQuanto = new javax.swing.JLabel();
        txtTroco = new javax.swing.JTextField();
        btnAvancar = new javax.swing.JButton();
        lblFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVoltar.setBackground(new java.awt.Color(255, 255, 255));
        btnVoltar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lblTitulo1.setFont(new java.awt.Font("Monotype Corsiva", 1, 48)); // NOI18N
        lblTitulo1.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo1.setText("Suas informações");
        getContentPane().add(lblTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 320, -1));

        lblTitulo2.setFont(new java.awt.Font("Monotype Corsiva", 1, 48)); // NOI18N
        lblTitulo2.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo2.setText("Pagamento");
        getContentPane().add(lblTitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 100, 210, -1));

        lblNome.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        lblNome.setForeground(new java.awt.Color(255, 255, 255));
        lblNome.setText("Seu nome");
        getContentPane().add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 90, -1));

        lblBairro.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        lblBairro.setForeground(new java.awt.Color(255, 255, 255));
        lblBairro.setText("Bairro");
        getContentPane().add(lblBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 60, -1));

        lblRua.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        lblRua.setForeground(new java.awt.Color(255, 255, 255));
        lblRua.setText("Rua");
        getContentPane().add(lblRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 50, -1));

        lblNumero.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        lblNumero.setForeground(new java.awt.Color(255, 255, 255));
        lblNumero.setText("N°");
        getContentPane().add(lblNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 290, 40, -1));

        lblTelefone.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        lblTelefone.setForeground(new java.awt.Color(255, 255, 255));
        lblTelefone.setText("Telefone");
        getContentPane().add(lblTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 90, -1));

        txtNome.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 200, 30));

        txtBairro.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(txtBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 200, 30));

        txtNumero.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 320, 40, 30));

        txtRua.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(txtRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 200, 30));

        txtTelefone.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(txtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 200, 30));

        lblPagamento.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        lblPagamento.setForeground(new java.awt.Color(255, 255, 255));
        lblPagamento.setText("Forma de pagamento");
        getContentPane().add(lblPagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 190, 200, -1));

        radioDebito.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(radioDebito);
        radioDebito.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        radioDebito.setForeground(new java.awt.Color(255, 255, 255));
        radioDebito.setText("Débito");
        radioDebito.setPreferredSize(new java.awt.Dimension(93, 31));
        radioDebito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioDebitoActionPerformed(evt);
            }
        });
        getContentPane().add(radioDebito, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 220, -1, -1));

        radioCredito.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(radioCredito);
        radioCredito.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        radioCredito.setForeground(new java.awt.Color(255, 255, 255));
        radioCredito.setText("Crédito");
        radioCredito.setPreferredSize(new java.awt.Dimension(93, 31));
        radioCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioCreditoActionPerformed(evt);
            }
        });
        getContentPane().add(radioCredito, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 260, -1, -1));

        radioDinheiro.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(radioDinheiro);
        radioDinheiro.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        radioDinheiro.setForeground(new java.awt.Color(255, 255, 255));
        radioDinheiro.setText("Dinheiro");
        radioDinheiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioDinheiroActionPerformed(evt);
            }
        });
        getContentPane().add(radioDinheiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 300, -1, -1));

        lblTroco.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        lblTroco.setForeground(new java.awt.Color(255, 255, 255));
        lblTroco.setText("Precisa de troco?");
        getContentPane().add(lblTroco, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 360, 200, -1));

        radioSim.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(radioSim);
        radioSim.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        radioSim.setForeground(new java.awt.Color(255, 255, 255));
        radioSim.setText("Sim");
        radioSim.setPreferredSize(new java.awt.Dimension(93, 31));
        radioSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSimActionPerformed(evt);
            }
        });
        getContentPane().add(radioSim, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 390, -1, -1));

        radioNao.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(radioNao);
        radioNao.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        radioNao.setForeground(new java.awt.Color(255, 255, 255));
        radioNao.setText("Não");
        radioNao.setPreferredSize(new java.awt.Dimension(93, 31));
        radioNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNaoActionPerformed(evt);
            }
        });
        getContentPane().add(radioNao, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 430, -1, -1));

        lblTrocoQuanto.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        lblTrocoQuanto.setForeground(new java.awt.Color(255, 255, 255));
        lblTrocoQuanto.setText("Troco para quanto?");
        getContentPane().add(lblTrocoQuanto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 190, 200, -1));

        txtTroco.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtTroco.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(txtTroco, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 220, 200, 30));

        btnAvancar.setBackground(new java.awt.Color(255, 255, 255));
        btnAvancar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnAvancar.setText("Avançar");
        btnAvancar.setPreferredSize(new java.awt.Dimension(118, 41));
        btnAvancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvancarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAvancar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 510, -1, -1));

        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/informacoes.png"))); // NOI18N
        getContentPane().add(lblFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        
        controller.voltarParaCardapioPedido();
        
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnAvancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvancarActionPerformed

        controller.navegarParaResumo();
        
    }//GEN-LAST:event_btnAvancarActionPerformed

    private void radioDinheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioDinheiroActionPerformed
        
        controller.pagar();
        
    }//GEN-LAST:event_radioDinheiroActionPerformed

    private void radioSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSimActionPerformed
        
        controller.precisaDeTroco();
        
    }//GEN-LAST:event_radioSimActionPerformed

    private void radioDebitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioDebitoActionPerformed
        
        controller.pagar();
        
    }//GEN-LAST:event_radioDebitoActionPerformed

    private void radioCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCreditoActionPerformed
        
        controller.pagar();
        
    }//GEN-LAST:event_radioCreditoActionPerformed

    private void radioNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNaoActionPerformed
        
        controller.precisaDeTroco();
        
    }//GEN-LAST:event_radioNaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Informacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Informacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Informacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Informacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Informacoes().setVisible(true);
            }
        });
    }

    public JLabel getLblTroco() {
        return lblTroco;
    }

    public void setLblTroco(JLabel lblTroco) {
        this.lblTroco = lblTroco;
    }

    public JLabel getLblTrocoQuanto() {
        return lblTrocoQuanto;
    }

    public void setLblTrocoQuanto(JLabel lblTrocoQuanto) {
        this.lblTrocoQuanto = lblTrocoQuanto;
    }

    public JRadioButton getRadioCredito() {
        return radioCredito;
    }

    public void setRadioCredito(JRadioButton radioCredito) {
        this.radioCredito = radioCredito;
    }

    public JRadioButton getRadioDebito() {
        return radioDebito;
    }

    public void setRadioDebito(JRadioButton radioDebito) {
        this.radioDebito = radioDebito;
    }

    public JRadioButton getRadioDinheiro() {
        return radioDinheiro;
    }

    public void setRadioDinheiro(JRadioButton radioDinheiro) {
        this.radioDinheiro = radioDinheiro;
    }

    public JRadioButton getRadioNao() {
        return radioNao;
    }

    public void setRadioNao(JRadioButton radioNao) {
        this.radioNao = radioNao;
    }

    public JRadioButton getRadioSim() {
        return radioSim;
    }

    public void setRadioSim(JRadioButton radioSim) {
        this.radioSim = radioSim;
    }

    public JTextField getTxtBairro() {
        return txtBairro;
    }

    public void setTxtBairro(JTextField txtBairro) {
        this.txtBairro = txtBairro;
    }

    public JTextField getTxtNome() {
        return txtNome;
    }

    public void setTxtNome(JTextField txtNome) {
        this.txtNome = txtNome;
    }

    public JTextField getTxtNumero() {
        return txtNumero;
    }

    public void setTxtNumero(JTextField txtNumero) {
        this.txtNumero = txtNumero;
    }

    public JTextField getTxtRua() {
        return txtRua;
    }

    public void setTxtRua(JTextField txtRua) {
        this.txtRua = txtRua;
    }

    public JTextField getTxtTelefone() {
        return txtTelefone;
    }

    public void setTxtTelefone(JTextField txtTelefone) {
        this.txtTelefone = txtTelefone;
    }

    public JTextField getTxtTroco() {
        return txtTroco;
    }

    public void setTxtTroco(JTextField txtTroco) {
        this.txtTroco = txtTroco;
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvancar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblPagamento;
    private javax.swing.JLabel lblRua;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JLabel lblTitulo2;
    private javax.swing.JLabel lblTroco;
    private javax.swing.JLabel lblTrocoQuanto;
    private javax.swing.JRadioButton radioCredito;
    private javax.swing.JRadioButton radioDebito;
    private javax.swing.JRadioButton radioDinheiro;
    private javax.swing.JRadioButton radioNao;
    private javax.swing.JRadioButton radioSim;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtRua;
    private javax.swing.JTextField txtTelefone;
    private javax.swing.JTextField txtTroco;
    // End of variables declaration//GEN-END:variables
}
