/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Casa
 */
public class Informacoes extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public Informacoes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVoltar = new javax.swing.JButton();
        lblTitulo1 = new javax.swing.JLabel();
        lblTitulo2 = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblBairro = new javax.swing.JLabel();
        lblRua = new javax.swing.JLabel();
        lblNumero = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtBairro = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        txtRua = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        lblPagamento = new javax.swing.JLabel();
        radioDebito = new javax.swing.JRadioButton();
        radioCredito = new javax.swing.JRadioButton();
        radioDinheiro = new javax.swing.JRadioButton();
        lblTroco = new javax.swing.JLabel();
        radioSim = new javax.swing.JRadioButton();
        radioNao = new javax.swing.JRadioButton();
        lblTrocoQuanto = new javax.swing.JLabel();
        txtTroco = new javax.swing.JTextField();
        btnAvancar = new javax.swing.JButton();
        lblFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVoltar.setBackground(new java.awt.Color(255, 255, 255));
        btnVoltar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnVoltar.setText("Voltar");
        getContentPane().add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lblTitulo1.setFont(new java.awt.Font("Monotype Corsiva", 1, 48)); // NOI18N
        lblTitulo1.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo1.setText("Suas informações");
        getContentPane().add(lblTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 320, -1));

        lblTitulo2.setFont(new java.awt.Font("Monotype Corsiva", 1, 48)); // NOI18N
        lblTitulo2.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo2.setText("Pagamento");
        getContentPane().add(lblTitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 100, 210, -1));

        lblNome.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        lblNome.setForeground(new java.awt.Color(255, 255, 255));
        lblNome.setText("Seu nome");
        getContentPane().add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 90, -1));

        lblBairro.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        lblBairro.setForeground(new java.awt.Color(255, 255, 255));
        lblBairro.setText("Bairro");
        getContentPane().add(lblBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 60, -1));

        lblRua.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        lblRua.setForeground(new java.awt.Color(255, 255, 255));
        lblRua.setText("Rua");
        getContentPane().add(lblRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 50, -1));

        lblNumero.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        lblNumero.setForeground(new java.awt.Color(255, 255, 255));
        lblNumero.setText("N°");
        getContentPane().add(lblNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 290, 40, -1));

        lblTelefone.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        lblTelefone.setForeground(new java.awt.Color(255, 255, 255));
        lblTelefone.setText("Telefone");
        getContentPane().add(lblTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 90, -1));
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 200, 30));
        getContentPane().add(txtBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 200, 30));
        getContentPane().add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 320, 40, 30));
        getContentPane().add(txtRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 200, 30));
        getContentPane().add(txtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 200, 30));

        lblPagamento.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        lblPagamento.setForeground(new java.awt.Color(255, 255, 255));
        lblPagamento.setText("Forma de pagamento");
        getContentPane().add(lblPagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 190, 200, -1));

        radioDebito.setBackground(new java.awt.Color(255, 255, 255));
        radioDebito.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        radioDebito.setForeground(new java.awt.Color(255, 255, 255));
        radioDebito.setText("Débito");
        radioDebito.setPreferredSize(new java.awt.Dimension(93, 31));
        getContentPane().add(radioDebito, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 220, -1, -1));

        radioCredito.setBackground(new java.awt.Color(255, 255, 255));
        radioCredito.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        radioCredito.setForeground(new java.awt.Color(255, 255, 255));
        radioCredito.setText("Crédito");
        radioCredito.setPreferredSize(new java.awt.Dimension(93, 31));
        getContentPane().add(radioCredito, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 260, -1, -1));

        radioDinheiro.setBackground(new java.awt.Color(255, 255, 255));
        radioDinheiro.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        radioDinheiro.setForeground(new java.awt.Color(255, 255, 255));
        radioDinheiro.setText("Dinheiro");
        getContentPane().add(radioDinheiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 300, -1, -1));

        lblTroco.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        lblTroco.setForeground(new java.awt.Color(255, 255, 255));
        lblTroco.setText("Precisa de troco?");
        getContentPane().add(lblTroco, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 360, 200, -1));

        radioSim.setBackground(new java.awt.Color(255, 255, 255));
        radioSim.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        radioSim.setForeground(new java.awt.Color(255, 255, 255));
        radioSim.setText("Sim");
        radioSim.setPreferredSize(new java.awt.Dimension(93, 31));
        getContentPane().add(radioSim, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 390, -1, -1));

        radioNao.setBackground(new java.awt.Color(255, 255, 255));
        radioNao.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        radioNao.setForeground(new java.awt.Color(255, 255, 255));
        radioNao.setText("Não");
        radioNao.setPreferredSize(new java.awt.Dimension(93, 31));
        getContentPane().add(radioNao, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 430, -1, -1));

        lblTrocoQuanto.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        lblTrocoQuanto.setForeground(new java.awt.Color(255, 255, 255));
        lblTrocoQuanto.setText("Troco para quanto?");
        getContentPane().add(lblTrocoQuanto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 190, 200, -1));
        getContentPane().add(txtTroco, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 220, 200, 30));

        btnAvancar.setBackground(new java.awt.Color(255, 255, 255));
        btnAvancar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnAvancar.setText("Avançar");
        btnAvancar.setPreferredSize(new java.awt.Dimension(118, 41));
        getContentPane().add(btnAvancar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 510, -1, -1));

        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/informacoes.png"))); // NOI18N
        getContentPane().add(lblFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Informacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Informacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Informacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Informacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Informacoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvancar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblPagamento;
    private javax.swing.JLabel lblRua;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JLabel lblTitulo2;
    private javax.swing.JLabel lblTroco;
    private javax.swing.JLabel lblTrocoQuanto;
    private javax.swing.JRadioButton radioCredito;
    private javax.swing.JRadioButton radioDebito;
    private javax.swing.JRadioButton radioDinheiro;
    private javax.swing.JRadioButton radioNao;
    private javax.swing.JRadioButton radioSim;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtRua;
    private javax.swing.JTextField txtTelefone;
    private javax.swing.JTextField txtTroco;
    // End of variables declaration//GEN-END:variables
}
