/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerResumo;

/**
 *
 * @author Casa
 */
public class Resumo extends javax.swing.JFrame {

    private final ControllerResumo controller;
    
    /**
     * Creates new form MenuPrincipal
     */
    public Resumo() {
        initComponents();
        this.controller = new ControllerResumo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVoltar = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        lblTituloPedido = new javax.swing.JLabel();
        lblPizzas = new javax.swing.JLabel();
        lblTituloInformacoes = new javax.swing.JLabel();
        lblInformacoes = new javax.swing.JLabel();
        lblTituloPagamento = new javax.swing.JLabel();
        lblPagamento = new javax.swing.JLabel();
        btnAvancar = new javax.swing.JButton();
        lblFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVoltar.setBackground(new java.awt.Color(255, 255, 255));
        btnVoltar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lblTitulo.setFont(new java.awt.Font("Monotype Corsiva", 1, 48)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Resumo");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 90, 150, -1));

        lblTituloPedido.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        lblTituloPedido.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloPedido.setText("Seu pedido");
        getContentPane().add(lblTituloPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 190, 110, -1));

        lblPizzas.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        lblPizzas.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblPizzas, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 220, 270, 340));

        lblTituloInformacoes.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        lblTituloInformacoes.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloInformacoes.setText("Suas informações");
        getContentPane().add(lblTituloInformacoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(597, 190, 170, -1));

        lblInformacoes.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        lblInformacoes.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblInformacoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(597, 220, 270, 340));

        lblTituloPagamento.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        lblTituloPagamento.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloPagamento.setText("Forma de pagamento");
        getContentPane().add(lblTituloPagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(918, 190, 200, -1));

        lblPagamento.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        lblPagamento.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblPagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(918, 220, 270, 240));

        btnAvancar.setBackground(new java.awt.Color(255, 255, 255));
        btnAvancar.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnAvancar.setText("Confirmar pedido");
        btnAvancar.setPreferredSize(new java.awt.Dimension(118, 41));
        btnAvancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvancarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAvancar, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 480, 270, -1));

        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/resumo.png"))); // NOI18N
        getContentPane().add(lblFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        
        controller.voltarParaInformacoes();
        
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnAvancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvancarActionPerformed
        
        controller.confirmarPedido();
        
    }//GEN-LAST:event_btnAvancarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Resumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Resumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Resumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Resumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Resumo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvancar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JLabel lblInformacoes;
    private javax.swing.JLabel lblPagamento;
    private javax.swing.JLabel lblPizzas;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloInformacoes;
    private javax.swing.JLabel lblTituloPagamento;
    private javax.swing.JLabel lblTituloPedido;
    // End of variables declaration//GEN-END:variables
}
